### ISSUE TITLE
Prepros name correction

### ISSUE THREAD

**Issue by ghost** [matt-harris/outline#10]
Sorry i did not see website github page. On the link prepros name is written wrong. Compiling Sass section.
http://outlinecss.co.uk/get-started.html
And is there a gulp and stylus versions?

**Comment by matt-harris** [comment]
Hi @atilkan thanks for the typo, now amended!

A fully commented Gulp file comes default with Outline.

There are no plans as yet to re create in Stylus.

Cheers
